---
- hosts: bbdd1
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - name: "Crear directorio para los backups"
      file:
        path: '{{ guest }}{{ ansible_date_time.date }}-{{ ansible_date_time.time}}/'
        mode: 0777
        owner: postgres
        state: directory
      become: yes
 
    - name: "Crear el backup"
      postgresql_db:
        state: dump
        name: '{{ nombre_bbdd }}'
        target: '{{ guest }}{{ ansible_date_time.date }}-{{ ansible_date_time.time}}/{{ nombre_bbdd }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.dump.gz'
      become: yes
      become_user: postgres

    - name: "Importar backup al nodo gestor"
      fetch:
        src: '{{ guest }}{{ ansible_date_time.date }}-{{ ansible_date_time.time}}/{{ nombre_bbdd }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.dump.gz'
        dest: '{{ host }}{{ ansible_hostname }}-{{ nombre_bbdd }}-{{ ansible_date_time.date }}-{{ ansible_date_time.time }}.dump.gz'
        flat: yes
